// let tokens = [];
const tokens = [
  ["color", "cor", "color()"],
  ["on", "liga", "on()"],
  ["off", "desliga", "off()"],
  ["lumin", "luminosidade", "lumin()"],
  ["timer", "timer", "timer()"],
  ["getTime()", "getTime", "getTime()"],
  ["ifsuldeminas", "ifsuldeminas", "ifsuldeminas"],
  ["ife", "ife", "ife"],
  ["elsee", "elsee", "elsee"],
  [">=", "operadorRelacional", "<, >, >=, <="],
  ["<=", "operadorRelacional", "<, >, >=, <="],
  [">", "operadorRelacional", "<, >, >=, <="],
  ["<", "operadorRelacional", "<, >, >=, <="],
  [";", "endln", ";"],
  ["for", "for", "for"],
  ["while", "while", "while"],
  ["try", "try", "try"],
  ["(", "ParenteseAbre", "("],
  [")", "ParenteseFecha", ")"],
  ["[", "colcheteAbre", "["],
  ["]", "colcheteFecha", "]"],
  ["catch", "catch", "catch"],
  ["null", "null", "null"],
  ["!", "negacao", "!"],
  ["||", "operadorLogico", "&&,||"],
  ["&&", "operadorLogico", "&&,||"],
  ["finally", "finally", "finally"],
  ["++", "incremento", "++"],
  ["==", "operadorRelacionalIgualDiferente", "==,!="],
  ["!=", "operadorRelacionalIgualDiferente", "==,!="],
  ["--", "incremento", "--"],
  ["boolean", "tipo", "boolean, enum, char, string,date"],
  ["enum", "tipo", "boolean, enum, char, string,date"],
  ["char", "tipo", "boolean, enum, char, string,date"],
  ["string", "tipo", "boolean, enum, char, string,date"],
  ["date", "tipo", "boolean, enum, char, string,date"],
  ["int", "tipoNumerico", "int, float, double"],
  ["float", "tipoNumerico", "int, float, double"],
  ["double", "tipoNumerico", "int, float, double"],
  ["=", "atribuicao", "="],
];
